export const CHANGE_GAME_REQUIREMENTS = 'CHANGE_GAME_REQUIREMENTS';
export const REMOVE_GAME_REQUIREMENTS = 'REMOVE_GAME_REQUIREMENTS';

export const SET_FILTERED_GAMES = 'SET_FILTERED_GAMES';
export const SET_GAMES = 'SET_GAMES';

export const ADD_WIDGET_DATA = 'ADD_WIDGET_DATA';
export const SET_WIDGETS_DATA = 'SET_WIDGETS_DATA';
export const REMOVE_WIDGET_DATA = 'REMOVE_WIDGET_DATA';

export const SHOW_ITEM_MODAL = 'SHOW_ITEM_MODAL';
export const UPDATE_ITEM_MODAL = 'UPDATE_ITEM_MODAL';
export const CLOSE_ITEM_MODAL = 'CLOSE_ITEM_MODAL';
