export const CHANGE_GAME_REQUIREMENTS = 'CHANGE_GAME_REQUIREMENTS';
export const REMOVE_GAME_REQUIREMENTS = 'REMOVE_GAME_REQUIREMENTS';
export const SET_FILTERED_GAMES = 'SET_FILTERED_GAMES';
export const SET_GAMES = 'SET_GAMES';
